# Generated by Django 2.2.1 on 2019-05-27 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoModelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoProd', models.IntegerField()),
                ('nombreProd', models.CharField(max_length=100)),
                ('detalleProd', models.CharField(max_length=200)),
                ('precioProd', models.IntegerField()),
                ('fechaIngreso', models.DateField()),
                ('stock', models.IntegerField()),
            ],
        ),
    ]
